-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for anggota
DROP TABLE IF EXISTS `anggota`;
CREATE TABLE `anggota` (
  `nrp` varchar(50) NOT NULL,
  `nama` varchar(255) NOT NULL,
  `pangkat` varchar(100) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`nrp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table anggota
INSERT INTO `anggota` VALUES ('001', 'ammar', 'jenderal', 1, '2026-08-03 01:58:22', '2026-08-03 01:58:22');
INSERT INTO `anggota` VALUES ('TEST-001', 'Test User', 'Sersan', 0, '2026-07-29 01:26:21', '2026-07-29 01:26:21');

SET FOREIGN_KEY_CHECKS=1;
