-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for anggota
DROP TABLE IF EXISTS `anggota`;
CREATE TABLE `anggota` (
  `nrp` varchar(50) NOT NULL,
  `nama` varchar(255) NOT NULL,
  `pangkat` varchar(100) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`nrp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table anggota
INSERT INTO `anggota` VALUES ('001', 'ammar', 'jenderal', 1, '2026-08-03 01:58:22', '2026-08-03 01:58:22');
INSERT INTO `anggota` VALUES ('TEST-001', 'Test User', 'Sersan', 0, '2026-07-29 01:26:21', '2026-07-29 01:26:21');

-- Table structure for barang
DROP TABLE IF EXISTS `barang`;
CREATE TABLE `barang` (
  `id_barang` int NOT NULL AUTO_INCREMENT,
  `barcode` varchar(50) DEFAULT NULL,
  `nama_barang` varchar(150) NOT NULL,
  `golongan` varchar(100) DEFAULT NULL,
  `harga_beli` decimal(15,2) DEFAULT '0.00',
  `stok_swalayan` int DEFAULT '0',
  `stok_grosir` int DEFAULT '0',
  `harga_swalayan` decimal(15,2) DEFAULT '0.00',
  `harga_grosir` decimal(15,2) DEFAULT '0.00',
  `satuan_swalayan` varchar(20) DEFAULT NULL,
  `satuan_grosir` varchar(20) DEFAULT NULL,
  `stok_minimal` int DEFAULT '10',
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id_barang`),
  UNIQUE KEY `barcode` (`barcode`),
  KEY `idx_is_active` (`is_active`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table barang
INSERT INTO `barang` VALUES (2, '899845101', 'Beras Maknyus 5kg', 'Sembako', '60000.00', 41, 25, '65000.00', '63000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (3, '899413170', 'Minyak Goreng Bimoli 2L', 'Sembako', '30000.00', 46, 33, '34000.00', '32000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (4, '899391528', 'Gula Pasir Gulaku 1kg', 'Sembako', '14000.00', 11, 19, '16000.00', '15000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (5, '899615197', 'Susu Bear Brand 189ml', 'Minuman', '9000.00', 52, 12, '10500.00', '10000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (6, '899103994', 'Sabun Mandi Lifebuoy 110g', 'Perawatan Diri', '3500.00', 14, 8, '4500.00', '4000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (7, '899229720', 'Shampoo Pantene 170ml', 'Perawatan Diri', '18000.00', 43, 7, '22000.00', '20000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (8, '899605132', 'Teh Pucuk Harum 350ml', 'Minuman', '3000.00', 31, 33, '4000.00', '3500.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (9, '899867992', 'Kopi Kapal Api Mix 25g', 'Minuman', '1200.00', 56, 8, '1500.00', '1300.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (10, '899005774', 'Telur Ayam Kampung 1kg', 'Sembako', '25000.00', 51, 11, '28000.00', '26500.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (11, '899384583', 'Rinso Anti Noda 770g', 'Kebutuhan Rumah', '20000.00', 59, 27, '24000.00', '22000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (12, '899237666', 'Pepsodent White 190g', 'Perawatan Diri', '9500.00', 41, 22, '12000.00', '11000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (13, '899923590', 'Mie Sedap Kuah Soto', 'Sembako', '2400.00', 53, 19, '3000.00', '2700.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (14, '899726149', 'Aqua Botol 600ml', 'Minuman', '2500.00', 54, 6, '3500.00', '3000.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (15, '899289270', 'Taro Snack Net 65g', 'Makanan Ringan', '4500.00', 50, 20, '6000.00', '5500.00', 'Pcs', 'Dus', 10, 1);
INSERT INTO `barang` VALUES (16, '123', 'Mie Gaga', NULL, '2000.00', 180, 0, '3000.00', '0.00', 'PCS', NULL, 10, 1);
INSERT INTO `barang` VALUES (17, '12345', 'Rokok Djarum', NULL, '10000.00', 47, 0, '12000.00', '0.00', 'Kotak', NULL, 10, 1);
INSERT INTO `barang` VALUES (18, '56789', 'Le Mineral', NULL, '14000.00', 0, 10, '0.00', '16000.00', NULL, 'DUS', 10, 1);
INSERT INTO `barang` VALUES (19, '10001', 'Depurasa', NULL, '20000.00', 0, 20, '0.00', '25000.00', NULL, 'DUS', 10, 1);
INSERT INTO `barang` VALUES (20, '123456789', 'Garam Rukyah', NULL, '125000.00', 110, 13, '15000.00', '150000.00', 'pcs', 'dus', 10, 1);

-- Table structure for detail_pembelian
DROP TABLE IF EXISTS `detail_pembelian`;
CREATE TABLE `detail_pembelian` (
  `id_detail` int NOT NULL AUTO_INCREMENT,
  `id_pembelian` int NOT NULL,
  `id_barang` int DEFAULT NULL,
  `snapshot_nama_barang` varchar(255) NOT NULL,
  `jumlah` int NOT NULL,
  `harga_satuan` decimal(15,2) NOT NULL,
  `subtotal` decimal(15,2) NOT NULL,
  PRIMARY KEY (`id_detail`),
  KEY `id_pembelian` (`id_pembelian`),
  KEY `id_barang` (`id_barang`),
  CONSTRAINT `detail_pembelian_ibfk_1` FOREIGN KEY (`id_pembelian`) REFERENCES `pembelian` (`id_pembelian`) ON DELETE CASCADE,
  CONSTRAINT `detail_pembelian_ibfk_2` FOREIGN KEY (`id_barang`) REFERENCES `barang` (`id_barang`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table detail_pembelian
INSERT INTO `detail_pembelian` VALUES (1, 1, 16, 'Mie Gaga', 150, '2000.00', '300000.00');
INSERT INTO `detail_pembelian` VALUES (2, 2, 16, 'Mie Gaga', 30, '2000.00', '60000.00');
INSERT INTO `detail_pembelian` VALUES (3, 3, 17, 'Rokok Djarum', 50, '10000.00', '500000.00');
INSERT INTO `detail_pembelian` VALUES (4, 4, 18, 'Le Mineral', 10, '14000.00', '140000.00');
INSERT INTO `detail_pembelian` VALUES (5, 5, 19, 'Depurasa', 20, '20000.00', '400000.00');
INSERT INTO `detail_pembelian` VALUES (6, 6, 20, 'Garam Rukyah', 1, '125000.00', '125000.00');

-- Table structure for detail_transaksi
DROP TABLE IF EXISTS `detail_transaksi`;
CREATE TABLE `detail_transaksi` (
  `id_detail` int NOT NULL AUTO_INCREMENT,
  `id_transaksi` int NOT NULL,
  `id_barang` int DEFAULT NULL,
  `quantity_barang` int NOT NULL,
  `harga_satuan` decimal(15,2) DEFAULT NULL,
  `diskon` decimal(15,2) DEFAULT '0.00',
  `subtotal` decimal(15,2) NOT NULL,
  `snapshot_nama_barang` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_detail`),
  KEY `idx_fk_transaksi` (`id_transaksi`),
  KEY `fk_detail_barang` (`id_barang`),
  CONSTRAINT `detail_transaksi_ibfk_1` FOREIGN KEY (`id_transaksi`) REFERENCES `transaksi` (`id_transaksi`),
  CONSTRAINT `fk_detail_barang` FOREIGN KEY (`id_barang`) REFERENCES `barang` (`id_barang`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table detail_transaksi
INSERT INTO `detail_transaksi` VALUES (1, 1, 10, 2, '28000.00', '0.00', '56000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (2, 2, NULL, 3, '2800.00', '0.00', '8400.00', NULL);
INSERT INTO `detail_transaksi` VALUES (3, 3, NULL, 2, '3000.00', '0.00', '6000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (4, 3, 3, 2, '34000.00', '0.00', '68000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (5, 3, 11, 3, '24000.00', '0.00', '72000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (6, 4, 3, 2, '34000.00', '0.00', '68000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (7, 5, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (8, 6, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (9, 6, 2, 3, '65000.00', '0.00', '195000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (10, 6, 10, 2, '28000.00', '0.00', '56000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (11, 6, 11, 2, '24000.00', '0.00', '48000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (12, 6, 13, 2, '3000.00', '0.00', '6000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (13, 7, NULL, 2, '2800.00', '0.00', '5600.00', NULL);
INSERT INTO `detail_transaksi` VALUES (14, 8, NULL, 3, '3000.00', '0.00', '9000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (15, 8, 4, 2, '16000.00', '0.00', '32000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (16, 8, 6, 1, '4500.00', '0.00', '4500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (17, 8, 8, 2, '4000.00', '0.00', '8000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (18, 9, 3, 3, '34000.00', '0.00', '102000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (19, 9, 5, 2, '10500.00', '0.00', '21000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (20, 9, 9, 2, '1500.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (21, 9, 10, 3, '28000.00', '0.00', '84000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (22, 9, 15, 1, '6000.00', '0.00', '6000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (23, 10, 3, 2, '34000.00', '0.00', '68000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (24, 10, 5, 2, '10500.00', '0.00', '21000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (25, 11, NULL, 2, '3000.00', '0.00', '6000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (26, 11, 7, 1, '22000.00', '0.00', '22000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (27, 11, 12, 1, '12000.00', '0.00', '12000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (28, 11, 14, 3, '3500.00', '0.00', '10500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (29, 11, 15, 2, '6000.00', '0.00', '12000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (30, 12, 2, 3, '63000.00', '0.00', '189000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (31, 12, 6, 3, '4000.00', '0.00', '12000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (32, 12, 12, 3, '11000.00', '0.00', '33000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (33, 13, 3, 1, '32000.00', '0.00', '32000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (34, 13, 5, 1, '10000.00', '0.00', '10000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (35, 13, 7, 3, '20000.00', '0.00', '60000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (36, 13, 8, 2, '3500.00', '0.00', '7000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (37, 13, 10, 1, '26500.00', '0.00', '26500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (38, 14, 8, 3, '4000.00', '0.00', '12000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (39, 14, 9, 3, '1500.00', '0.00', '4500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (40, 15, 3, 1, '32000.00', '0.00', '32000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (41, 15, 11, 2, '22000.00', '0.00', '44000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (42, 15, 12, 3, '11000.00', '0.00', '33000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (43, 15, 15, 1, '5500.00', '0.00', '5500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (44, 16, NULL, 3, '2800.00', '0.00', '8400.00', NULL);
INSERT INTO `detail_transaksi` VALUES (45, 16, 2, 3, '63000.00', '0.00', '189000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (46, 17, 15, 1, '5500.00', '0.00', '5500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (47, 18, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (48, 18, 6, 3, '4500.00', '0.00', '13500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (49, 19, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (50, 20, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (51, 21, 17, 3, NULL, '0.00', '36000.00', 'Rokok Djarum');
INSERT INTO `detail_transaksi` VALUES (52, 23, 20, 2, NULL, '0.00', '300000.00', 'Garam Rukyah');

-- Table structure for pembelian
DROP TABLE IF EXISTS `pembelian`;
CREATE TABLE `pembelian` (
  `id_pembelian` int NOT NULL AUTO_INCREMENT,
  `kategori` enum('Swalayan','Grosir') NOT NULL,
  `status` enum('Menunggu','Diterima','Dimutasi','Ditunda') DEFAULT 'Menunggu',
  `waktu_pembelian` datetime DEFAULT CURRENT_TIMESTAMP,
  `id_supplier` int NOT NULL,
  `id_pengguna` int NOT NULL,
  `total_biaya` decimal(15,2) DEFAULT '0.00',
  PRIMARY KEY (`id_pembelian`),
  KEY `id_supplier` (`id_supplier`),
  KEY `id_pengguna` (`id_pengguna`),
  CONSTRAINT `pembelian_ibfk_1` FOREIGN KEY (`id_supplier`) REFERENCES `supplier` (`id_supplier`) ON DELETE RESTRICT,
  CONSTRAINT `pembelian_ibfk_2` FOREIGN KEY (`id_pengguna`) REFERENCES `pengguna` (`id_pengguna`) ON DELETE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table pembelian
INSERT INTO `pembelian` VALUES (1, 'Swalayan', 'Dimutasi', '2026-08-03 02:29:07', 4, 1, '300000.00');
INSERT INTO `pembelian` VALUES (2, 'Swalayan', 'Dimutasi', '2026-08-03 02:54:02', 5, 1, '60000.00');
INSERT INTO `pembelian` VALUES (3, 'Swalayan', 'Dimutasi', '2026-08-03 02:55:04', 6, 1, '500000.00');
INSERT INTO `pembelian` VALUES (4, 'Grosir', 'Dimutasi', '2026-08-03 03:10:30', 7, 1, '140000.00');
INSERT INTO `pembelian` VALUES (5, 'Grosir', 'Dimutasi', '2026-08-03 03:12:37', 8, 1, '400000.00');
INSERT INTO `pembelian` VALUES (6, 'Grosir', 'Dimutasi', '2026-08-04 01:02:12', 9, 1, '125000.00');

-- Table structure for pengguna
DROP TABLE IF EXISTS `pengguna`;
CREATE TABLE `pengguna` (
  `id_pengguna` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `nama_pengguna` varchar(100) NOT NULL,
  `id_role` int DEFAULT NULL,
  PRIMARY KEY (`id_pengguna`),
  UNIQUE KEY `username` (`username`),
  KEY `pengguna_ibfk_1` (`id_role`),
  CONSTRAINT `pengguna_ibfk_1` FOREIGN KEY (`id_role`) REFERENCES `role` (`id_role`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table pengguna
INSERT INTO `pengguna` VALUES (1, 'admin', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Administrator', 1);
INSERT INTO `pengguna` VALUES (3, 'kasir_baru', '$2b$10$9hfX6WHJe0rM3UmZGl2nGOVF4K1bt7SjjM6fO3dDE9pmfyjP3l6yq', 'Kasir Toko', 2);
INSERT INTO `pengguna` VALUES (4, 'test1_grosir', '$2b$10$p0H1qmZfiDa5KYNfud0SSe9tEQfND7x3G6HEHnjR.9sE10SJ/Ob22', 'Ammar', 3);
INSERT INTO `pengguna` VALUES (5, 'aji', '$2b$10$VC5ObahiZHBGql0b51MpuuiNiCr/o4aqRn2bhK1tX9CC00qAz2Xy.', 'Aji Kartiko Hartanto', 3);
INSERT INTO `pengguna` VALUES (6, 'ammar', '$2b$10$EEQox/Iypa9DXA.VAUr9mOW8i04aZ.R/cAB2ScC1jDD.wgotV0c26', 'Ammar Bagas Fathurrahman Wantoro', 2);

-- Table structure for role
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `id_role` int NOT NULL AUTO_INCREMENT,
  `nama_role` varchar(50) NOT NULL,
  `deskripsi` text,
  PRIMARY KEY (`id_role`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table role
INSERT INTO `role` VALUES (1, 'Admin Koperasi', 'Administrator sistem koperasi');
INSERT INTO `role` VALUES (2, 'Kasir Swalayan', 'Pegawai kasir di area swalayan');
INSERT INTO `role` VALUES (3, 'Kasir Grosir', 'Pegawai kasir di area swalayan');

-- Table structure for supplier
DROP TABLE IF EXISTS `supplier`;
CREATE TABLE `supplier` (
  `id_supplier` int NOT NULL AUTO_INCREMENT,
  `nama_supplier` varchar(255) NOT NULL,
  `kontak` varchar(100) DEFAULT NULL,
  `alamat` text,
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id_supplier`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplier
INSERT INTO `supplier` VALUES (1, 'PT. ABC Pemasok', '0812345', 'Jakarta', 1);
INSERT INTO `supplier` VALUES (2, 'PT. ABC Pemasok', '0812345', 'Jakarta', 1);
INSERT INTO `supplier` VALUES (3, 'PT. ABC Pemasok', '0812345', 'Jakarta', 1);
INSERT INTO `supplier` VALUES (4, 'PT.Gulaku', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (5, 'PT. ABC', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (6, 'Pt.Djarum', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (7, 'PT.ABC', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (8, 'PT.Indofood', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (9, 'asdw', NULL, NULL, 1);

-- Table structure for transaksi
DROP TABLE IF EXISTS `transaksi`;
CREATE TABLE `transaksi` (
  `id_transaksi` int NOT NULL AUTO_INCREMENT,
  `waktu_transaksi` datetime NOT NULL,
  `total_bayar` decimal(15,2) DEFAULT '0.00',
  `jenis_transaksi` varchar(50) DEFAULT NULL,
  `id_pengguna` int DEFAULT NULL,
  `nrp` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id_transaksi`),
  KEY `transaksi_ibfk_1` (`id_pengguna`),
  KEY `fk_transaksi_anggota` (`nrp`),
  KEY `idx_waktu_transaksi` (`waktu_transaksi`),
  CONSTRAINT `fk_transaksi_anggota` FOREIGN KEY (`nrp`) REFERENCES `anggota` (`nrp`) ON DELETE SET NULL,
  CONSTRAINT `transaksi_ibfk_1` FOREIGN KEY (`id_pengguna`) REFERENCES `pengguna` (`id_pengguna`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table transaksi
INSERT INTO `transaksi` VALUES (1, '2026-07-31 21:01:23', '56000.00', 'Swalayan', 4, NULL);
INSERT INTO `transaksi` VALUES (2, '2026-08-02 02:18:23', '8400.00', 'Grosir', 5, NULL);
INSERT INTO `transaksi` VALUES (3, '2026-07-31 18:18:23', '146000.00', 'Swalayan', 4, NULL);
INSERT INTO `transaksi` VALUES (4, '2026-07-28 05:32:23', '68000.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (5, '2026-08-03 05:36:23', '3000.00', 'Swalayan', 5, NULL);
INSERT INTO `transaksi` VALUES (6, '2026-07-27 20:14:23', '308000.00', 'Swalayan', 3, NULL);
INSERT INTO `transaksi` VALUES (7, '2026-07-27 23:41:23', '5600.00', 'Grosir', 4, NULL);
INSERT INTO `transaksi` VALUES (8, '2026-07-31 02:45:23', '53500.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (9, '2026-07-27 22:02:23', '216000.00', 'Swalayan', 4, NULL);
INSERT INTO `transaksi` VALUES (10, '2026-07-29 19:55:23', '89000.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (11, '2026-08-01 02:04:23', '62500.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (12, '2026-07-31 19:01:23', '234000.00', 'Grosir', 5, NULL);
INSERT INTO `transaksi` VALUES (13, '2026-08-01 22:05:23', '135500.00', 'Grosir', 6, NULL);
INSERT INTO `transaksi` VALUES (14, '2026-07-29 21:26:23', '16500.00', 'Swalayan', 3, NULL);
INSERT INTO `transaksi` VALUES (15, '2026-07-29 23:02:23', '114500.00', 'Grosir', 5, NULL);
INSERT INTO `transaksi` VALUES (16, '2026-07-31 23:17:23', '197400.00', 'Grosir', 6, NULL);
INSERT INTO `transaksi` VALUES (17, '2026-08-01 05:00:23', '5500.00', 'Grosir', 3, NULL);
INSERT INTO `transaksi` VALUES (18, '2026-07-27 18:39:23', '16500.00', 'Swalayan', 3, NULL);
INSERT INTO `transaksi` VALUES (19, '2026-07-29 07:12:23', '3000.00', 'Swalayan', 6, NULL);
INSERT INTO `transaksi` VALUES (20, '2026-07-30 19:43:23', '3000.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (21, '2026-08-03 03:04:51', '36000.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (23, '2026-08-04 01:10:19', '300000.00', 'Grosir', 1, NULL);

SET FOREIGN_KEY_CHECKS=1;
