-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for detail_pembelian
DROP TABLE IF EXISTS `detail_pembelian`;
CREATE TABLE `detail_pembelian` (
  `id_detail` int NOT NULL AUTO_INCREMENT,
  `id_pembelian` int NOT NULL,
  `id_barang` int DEFAULT NULL,
  `snapshot_nama_barang` varchar(255) NOT NULL,
  `jumlah` int NOT NULL,
  `harga_satuan` decimal(15,2) NOT NULL,
  `subtotal` decimal(15,2) NOT NULL,
  PRIMARY KEY (`id_detail`),
  KEY `id_pembelian` (`id_pembelian`),
  KEY `id_barang` (`id_barang`),
  CONSTRAINT `detail_pembelian_ibfk_1` FOREIGN KEY (`id_pembelian`) REFERENCES `pembelian` (`id_pembelian`) ON DELETE CASCADE,
  CONSTRAINT `detail_pembelian_ibfk_2` FOREIGN KEY (`id_barang`) REFERENCES `barang` (`id_barang`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table detail_pembelian
INSERT INTO `detail_pembelian` VALUES (1, 1, 16, 'Mie Gaga', 150, '2000.00', '300000.00');
INSERT INTO `detail_pembelian` VALUES (2, 2, 16, 'Mie Gaga', 30, '2000.00', '60000.00');
INSERT INTO `detail_pembelian` VALUES (3, 3, 17, 'Rokok Djarum', 50, '10000.00', '500000.00');
INSERT INTO `detail_pembelian` VALUES (4, 4, 18, 'Le Mineral', 10, '14000.00', '140000.00');
INSERT INTO `detail_pembelian` VALUES (5, 5, 19, 'Depurasa', 20, '20000.00', '400000.00');
INSERT INTO `detail_pembelian` VALUES (6, 6, 20, 'Garam Rukyah', 1, '125000.00', '125000.00');

SET FOREIGN_KEY_CHECKS=1;
