-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for detail_transaksi
DROP TABLE IF EXISTS `detail_transaksi`;
CREATE TABLE `detail_transaksi` (
  `id_detail` int NOT NULL AUTO_INCREMENT,
  `id_transaksi` int NOT NULL,
  `id_barang` int DEFAULT NULL,
  `quantity_barang` int NOT NULL,
  `harga_satuan` decimal(15,2) DEFAULT NULL,
  `diskon` decimal(15,2) DEFAULT '0.00',
  `subtotal` decimal(15,2) NOT NULL,
  `snapshot_nama_barang` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_detail`),
  KEY `idx_fk_transaksi` (`id_transaksi`),
  KEY `fk_detail_barang` (`id_barang`),
  CONSTRAINT `detail_transaksi_ibfk_1` FOREIGN KEY (`id_transaksi`) REFERENCES `transaksi` (`id_transaksi`),
  CONSTRAINT `fk_detail_barang` FOREIGN KEY (`id_barang`) REFERENCES `barang` (`id_barang`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table detail_transaksi
INSERT INTO `detail_transaksi` VALUES (1, 1, 10, 2, '28000.00', '0.00', '56000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (2, 2, NULL, 3, '2800.00', '0.00', '8400.00', NULL);
INSERT INTO `detail_transaksi` VALUES (3, 3, NULL, 2, '3000.00', '0.00', '6000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (4, 3, 3, 2, '34000.00', '0.00', '68000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (5, 3, 11, 3, '24000.00', '0.00', '72000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (6, 4, 3, 2, '34000.00', '0.00', '68000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (7, 5, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (8, 6, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (9, 6, 2, 3, '65000.00', '0.00', '195000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (10, 6, 10, 2, '28000.00', '0.00', '56000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (11, 6, 11, 2, '24000.00', '0.00', '48000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (12, 6, 13, 2, '3000.00', '0.00', '6000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (13, 7, NULL, 2, '2800.00', '0.00', '5600.00', NULL);
INSERT INTO `detail_transaksi` VALUES (14, 8, NULL, 3, '3000.00', '0.00', '9000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (15, 8, 4, 2, '16000.00', '0.00', '32000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (16, 8, 6, 1, '4500.00', '0.00', '4500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (17, 8, 8, 2, '4000.00', '0.00', '8000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (18, 9, 3, 3, '34000.00', '0.00', '102000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (19, 9, 5, 2, '10500.00', '0.00', '21000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (20, 9, 9, 2, '1500.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (21, 9, 10, 3, '28000.00', '0.00', '84000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (22, 9, 15, 1, '6000.00', '0.00', '6000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (23, 10, 3, 2, '34000.00', '0.00', '68000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (24, 10, 5, 2, '10500.00', '0.00', '21000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (25, 11, NULL, 2, '3000.00', '0.00', '6000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (26, 11, 7, 1, '22000.00', '0.00', '22000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (27, 11, 12, 1, '12000.00', '0.00', '12000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (28, 11, 14, 3, '3500.00', '0.00', '10500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (29, 11, 15, 2, '6000.00', '0.00', '12000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (30, 12, 2, 3, '63000.00', '0.00', '189000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (31, 12, 6, 3, '4000.00', '0.00', '12000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (32, 12, 12, 3, '11000.00', '0.00', '33000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (33, 13, 3, 1, '32000.00', '0.00', '32000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (34, 13, 5, 1, '10000.00', '0.00', '10000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (35, 13, 7, 3, '20000.00', '0.00', '60000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (36, 13, 8, 2, '3500.00', '0.00', '7000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (37, 13, 10, 1, '26500.00', '0.00', '26500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (38, 14, 8, 3, '4000.00', '0.00', '12000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (39, 14, 9, 3, '1500.00', '0.00', '4500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (40, 15, 3, 1, '32000.00', '0.00', '32000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (41, 15, 11, 2, '22000.00', '0.00', '44000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (42, 15, 12, 3, '11000.00', '0.00', '33000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (43, 15, 15, 1, '5500.00', '0.00', '5500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (44, 16, NULL, 3, '2800.00', '0.00', '8400.00', NULL);
INSERT INTO `detail_transaksi` VALUES (45, 16, 2, 3, '63000.00', '0.00', '189000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (46, 17, 15, 1, '5500.00', '0.00', '5500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (47, 18, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (48, 18, 6, 3, '4500.00', '0.00', '13500.00', NULL);
INSERT INTO `detail_transaksi` VALUES (49, 19, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (50, 20, NULL, 1, '3000.00', '0.00', '3000.00', NULL);
INSERT INTO `detail_transaksi` VALUES (51, 21, 17, 3, NULL, '0.00', '36000.00', 'Rokok Djarum');
INSERT INTO `detail_transaksi` VALUES (52, 23, 20, 2, NULL, '0.00', '300000.00', 'Garam Rukyah');

SET FOREIGN_KEY_CHECKS=1;
