-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for pembelian
DROP TABLE IF EXISTS `pembelian`;
CREATE TABLE `pembelian` (
  `id_pembelian` int NOT NULL AUTO_INCREMENT,
  `kategori` enum('Swalayan','Grosir') NOT NULL,
  `status` enum('Menunggu','Diterima','Dimutasi','Ditunda') DEFAULT 'Menunggu',
  `waktu_pembelian` datetime DEFAULT CURRENT_TIMESTAMP,
  `id_supplier` int NOT NULL,
  `id_pengguna` int NOT NULL,
  `total_biaya` decimal(15,2) DEFAULT '0.00',
  PRIMARY KEY (`id_pembelian`),
  KEY `id_supplier` (`id_supplier`),
  KEY `id_pengguna` (`id_pengguna`),
  CONSTRAINT `pembelian_ibfk_1` FOREIGN KEY (`id_supplier`) REFERENCES `supplier` (`id_supplier`) ON DELETE RESTRICT,
  CONSTRAINT `pembelian_ibfk_2` FOREIGN KEY (`id_pengguna`) REFERENCES `pengguna` (`id_pengguna`) ON DELETE RESTRICT
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table pembelian
INSERT INTO `pembelian` VALUES (1, 'Swalayan', 'Dimutasi', '2026-08-03 02:29:07', 4, 1, '300000.00');
INSERT INTO `pembelian` VALUES (2, 'Swalayan', 'Dimutasi', '2026-08-03 02:54:02', 5, 1, '60000.00');
INSERT INTO `pembelian` VALUES (3, 'Swalayan', 'Dimutasi', '2026-08-03 02:55:04', 6, 1, '500000.00');
INSERT INTO `pembelian` VALUES (4, 'Grosir', 'Dimutasi', '2026-08-03 03:10:30', 7, 1, '140000.00');
INSERT INTO `pembelian` VALUES (5, 'Grosir', 'Dimutasi', '2026-08-03 03:12:37', 8, 1, '400000.00');
INSERT INTO `pembelian` VALUES (6, 'Grosir', 'Dimutasi', '2026-08-04 01:02:12', 9, 1, '125000.00');

SET FOREIGN_KEY_CHECKS=1;
