-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for pengguna
DROP TABLE IF EXISTS `pengguna`;
CREATE TABLE `pengguna` (
  `id_pengguna` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `nama_pengguna` varchar(100) NOT NULL,
  `id_role` int DEFAULT NULL,
  PRIMARY KEY (`id_pengguna`),
  UNIQUE KEY `username` (`username`),
  KEY `pengguna_ibfk_1` (`id_role`),
  CONSTRAINT `pengguna_ibfk_1` FOREIGN KEY (`id_role`) REFERENCES `role` (`id_role`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table pengguna
INSERT INTO `pengguna` VALUES (1, 'admin_sistem', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Admin Sistem Utama', 1);
INSERT INTO `pengguna` VALUES (2, 'kasir_swalayan', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Kasir Swalayan 1', 2);
INSERT INTO `pengguna` VALUES (3, 'kasir_grosir', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Kasir Grosir 1', 3);
INSERT INTO `pengguna` VALUES (4, 'admin_pembelian', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Admin Pembelian', 4);
INSERT INTO `pengguna` VALUES (5, 'admin_order', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Admin Order', 5);
INSERT INTO `pengguna` VALUES (6, 'admin_penjualan', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Admin Penjualan (Mutasi)', 6);
INSERT INTO `pengguna` VALUES (7, 'admin_gudang', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Admin Gudang', 7);

SET FOREIGN_KEY_CHECKS=1;
