-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for pengguna
DROP TABLE IF EXISTS `pengguna`;
CREATE TABLE `pengguna` (
  `id_pengguna` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `nama_pengguna` varchar(100) NOT NULL,
  `id_role` int DEFAULT NULL,
  PRIMARY KEY (`id_pengguna`),
  UNIQUE KEY `username` (`username`),
  KEY `pengguna_ibfk_1` (`id_role`),
  CONSTRAINT `pengguna_ibfk_1` FOREIGN KEY (`id_role`) REFERENCES `role` (`id_role`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table pengguna
INSERT INTO `pengguna` VALUES (1, 'admin', '$2b$10$vXCgGyD.ebnWEyrIm/FCMOkQI/gPSnJNmYg3Kb8HW614EzhdWZXj2', 'Administrator', 1);
INSERT INTO `pengguna` VALUES (3, 'kasir_baru', '$2b$10$9hfX6WHJe0rM3UmZGl2nGOVF4K1bt7SjjM6fO3dDE9pmfyjP3l6yq', 'Kasir Toko', 2);
INSERT INTO `pengguna` VALUES (4, 'test1_grosir', '$2b$10$p0H1qmZfiDa5KYNfud0SSe9tEQfND7x3G6HEHnjR.9sE10SJ/Ob22', 'Ammar', 3);
INSERT INTO `pengguna` VALUES (5, 'aji', '$2b$10$VC5ObahiZHBGql0b51MpuuiNiCr/o4aqRn2bhK1tX9CC00qAz2Xy.', 'Aji Kartiko Hartanto', 3);
INSERT INTO `pengguna` VALUES (6, 'ammar', '$2b$10$EEQox/Iypa9DXA.VAUr9mOW8i04aZ.R/cAB2ScC1jDD.wgotV0c26', 'Ammar Bagas Fathurrahman Wantoro', 2);

SET FOREIGN_KEY_CHECKS=1;
