-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for role
DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `id_role` int NOT NULL AUTO_INCREMENT,
  `nama_role` varchar(50) NOT NULL,
  `deskripsi` text,
  PRIMARY KEY (`id_role`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table role
INSERT INTO `role` VALUES (1, 'Admin Koperasi', 'Administrator sistem koperasi');
INSERT INTO `role` VALUES (2, 'Kasir Swalayan', 'Pegawai kasir di area swalayan');
INSERT INTO `role` VALUES (3, 'Kasir Grosir', 'Pegawai kasir di area swalayan');

SET FOREIGN_KEY_CHECKS=1;
