-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for supplier
DROP TABLE IF EXISTS `supplier`;
CREATE TABLE `supplier` (
  `id_supplier` int NOT NULL AUTO_INCREMENT,
  `nama_supplier` varchar(255) NOT NULL,
  `kontak` varchar(100) DEFAULT NULL,
  `alamat` text,
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id_supplier`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplier
INSERT INTO `supplier` VALUES (1, 'PT. ABC Pemasok', '0812345', 'Jakarta', 1);
INSERT INTO `supplier` VALUES (2, 'PT. ABC Pemasok', '0812345', 'Jakarta', 1);
INSERT INTO `supplier` VALUES (3, 'PT. ABC Pemasok', '0812345', 'Jakarta', 1);
INSERT INTO `supplier` VALUES (4, 'PT.Gulaku', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (5, 'PT. ABC', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (6, 'Pt.Djarum', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (7, 'PT.ABC', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (8, 'PT.Indofood', NULL, NULL, 1);
INSERT INTO `supplier` VALUES (9, 'asdw', NULL, NULL, 1);

SET FOREIGN_KEY_CHECKS=1;
