-- Database export for db_koperasi
-- Generated by Node.js

SET FOREIGN_KEY_CHECKS=0;

-- Table structure for transaksi
DROP TABLE IF EXISTS `transaksi`;
CREATE TABLE `transaksi` (
  `id_transaksi` int NOT NULL AUTO_INCREMENT,
  `waktu_transaksi` datetime NOT NULL,
  `total_bayar` decimal(15,2) DEFAULT '0.00',
  `jenis_transaksi` varchar(50) DEFAULT NULL,
  `id_pengguna` int DEFAULT NULL,
  `nrp` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id_transaksi`),
  KEY `transaksi_ibfk_1` (`id_pengguna`),
  KEY `fk_transaksi_anggota` (`nrp`),
  KEY `idx_waktu_transaksi` (`waktu_transaksi`),
  CONSTRAINT `fk_transaksi_anggota` FOREIGN KEY (`nrp`) REFERENCES `anggota` (`nrp`) ON DELETE SET NULL,
  CONSTRAINT `transaksi_ibfk_1` FOREIGN KEY (`id_pengguna`) REFERENCES `pengguna` (`id_pengguna`)
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table transaksi
INSERT INTO `transaksi` VALUES (1, '2026-07-31 21:01:23', '56000.00', 'Swalayan', 4, NULL);
INSERT INTO `transaksi` VALUES (2, '2026-08-02 02:18:23', '8400.00', 'Grosir', 5, NULL);
INSERT INTO `transaksi` VALUES (3, '2026-07-31 18:18:23', '146000.00', 'Swalayan', 4, NULL);
INSERT INTO `transaksi` VALUES (4, '2026-07-28 05:32:23', '68000.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (5, '2026-08-03 05:36:23', '3000.00', 'Swalayan', 5, NULL);
INSERT INTO `transaksi` VALUES (6, '2026-07-27 20:14:23', '308000.00', 'Swalayan', 3, NULL);
INSERT INTO `transaksi` VALUES (7, '2026-07-27 23:41:23', '5600.00', 'Grosir', 4, NULL);
INSERT INTO `transaksi` VALUES (8, '2026-07-31 02:45:23', '53500.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (9, '2026-07-27 22:02:23', '216000.00', 'Swalayan', 4, NULL);
INSERT INTO `transaksi` VALUES (10, '2026-07-29 19:55:23', '89000.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (11, '2026-08-01 02:04:23', '62500.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (12, '2026-07-31 19:01:23', '234000.00', 'Grosir', 5, NULL);
INSERT INTO `transaksi` VALUES (13, '2026-08-01 22:05:23', '135500.00', 'Grosir', 6, NULL);
INSERT INTO `transaksi` VALUES (14, '2026-07-29 21:26:23', '16500.00', 'Swalayan', 3, NULL);
INSERT INTO `transaksi` VALUES (15, '2026-07-29 23:02:23', '114500.00', 'Grosir', 5, NULL);
INSERT INTO `transaksi` VALUES (16, '2026-07-31 23:17:23', '197400.00', 'Grosir', 6, NULL);
INSERT INTO `transaksi` VALUES (17, '2026-08-01 05:00:23', '5500.00', 'Grosir', 3, NULL);
INSERT INTO `transaksi` VALUES (18, '2026-07-27 18:39:23', '16500.00', 'Swalayan', 3, NULL);
INSERT INTO `transaksi` VALUES (19, '2026-07-29 07:12:23', '3000.00', 'Swalayan', 6, NULL);
INSERT INTO `transaksi` VALUES (20, '2026-07-30 19:43:23', '3000.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (21, '2026-08-03 03:04:51', '36000.00', 'Swalayan', 1, NULL);
INSERT INTO `transaksi` VALUES (23, '2026-08-04 01:10:19', '300000.00', 'Grosir', 1, NULL);

SET FOREIGN_KEY_CHECKS=1;
